services:
  - type: web
    name: cortex-ai-workspace
    env: python
    plan: free
    buildCommand: pip install --upgrade pip setuptools wheel && pip install --no-cache-dir -r requirements-minimal.txt
    startCommand: gunicorn app_minimal:app -w 1 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
      - key: ENVIRONMENT
        value: production
    autoDeploy: false

databases:
  - name: cortex-ai-db
    plan: free
    databaseName: cortex_ai_workspace
    user: cortex_user